### ISSUE TITLE
Fix save issues in test suite

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/GeoTables.jl#34]
The tests in the "save" test set are failing with some combinations of file formats. We need to fix them all.

**Comment by eliascarv** [comment]
### 1st Problem
ArchGDAL.jl does not support write `Date` or `Time` columns, only `DateTime`, even though the `AG.OGRFieldType` enum has variants for these types:
```
julia> convert(AG.OGRFieldType, DateTime)
OFTDateTime::OGRFieldType = 11

julia> convert(AG.OGRFieldType, Date)
OFTDate::OGRFieldType = 9

julia> convert(AG.OGRFieldType, Time)
OFTTime::OGRFieldType = 10
```
Methods that support `TimeType`:
```
julia> methods(AG.setfield!, (AG.AbstractFeature, Integer, TimeType))
# 1 method for generic function "setfield!" from ArchGDAL:
 [1] setfield!(feature::ArchGDAL.AbstractFeature, i::Integer, dt::DateTime)
     @ ~/.julia/packages/ArchGDAL/R3wJR/src/ogr/feature.jl:705
```
Note: `TimeType` is the supertype of `DateTime`, `Date` and `Time`.

### 2nd Problem
GeoJSON.jl reads and writes `DateTime`, `Date` and `Time` columns as `String`, because JSON format does not support these types:

![Captura de tela de 2023-06-29 10-30-48](https://github.com/JuliaEarth/GeoTables.jl/assets/73039601/bd8be316-8ff0-40a3-a90c-cfae78f7f809)

![Captura de tela de 2023-06-29 10-35-04](https://github.com/JuliaEarth/GeoTables.jl/assets/73039601/7881019a-7b2f-4513-83d3-ffb8ac0aa52c)
